"""testing

Revision ID: c09ef4ff8d8a
Revises: 2816e6be5148
Create Date: 2025-10-20 12:04:11.841170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09ef4ff8d8a'
down_revision = '2816e6be5148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
